id: P009625
initial_creation_type: ocr
source_metadata:
  id: bdr:W30145
  title: ཞལ་ལྕེ་ཕྱོགས་བསྡུས།
  author: ''
  volumes:
    0810abecf5f74a068e55906ac3021cb1:
      image_group_id: I1GS105539
      title: ''
      volume_number: 1
      total_pages: 292
      base_file: v001.txt
